---
- name: "Run all ansible playbooks"
  hosts: all

# - name: "Run Apache playbook"
#   import_playbook: apache/playbook.yml

- name: "Run Nginx playbook"
  import_playbook: nginx/playbook.yml

- name: "Run Docker installation playbook"
  import_playbook: docker/install.yml

- name: "Run Docker deployment playbook"
  import_playbook: docker/deploy.yml
