---
- name: "LDAP server + LAM"
  hosts: all
  become: true
  vars_files:
    - ../config.yml

  tasks:
    - name: Install LDAP packages
      apt:
        name: "{{ item }}"
        update_cache: true
        state: latest
      with_items:
        - slapd
        - ldap-utils
        - ldap-account-manager
      
    - name: "Configure slapd admin password"
      debconf:
        name: slapd
        question: "slapd/{{ item }}"
        value: "{{ ldap_password }}"
        vtype: password
      with_items:
        - password1
        - password2

    - name: Set up the ldap configuration
      template:
        src: files/ldap.conf.j2
        dest: /etc/ldap/ldap.conf
        mode: "644"
        force: true

    - name: Set up the slapd configuration
      template:
        src: files/slapd.j2
        dest: /etc/default/slapd
        mode: "644"
        force: true
      notify: Restart slapd

  handlers:
    - name: Restart slapd
      service:
        name: slapd
        state: restarted
