---
- name: "Apache server"
  hosts: all
  become: true
  vars_files:
    - ../vars/default.yml

  tasks:
    - name: "Install dependencies"
      apt:
        name: "{{ item }}"
        state: "latest"
        update_cache: true
        force_apt_get: true
      with_items:
        - "aptitude"
        - "snapd"

    - name: "Enable the snapd service"
      service:
        name: snapd
        state: started
        enabled: true

    - name: "Install Apache"
      apt: name=apache2 update_cache=yes state=latest

    - name: "Create document root"
      file:
        path: "/var/www/{{ server_host }}"
        state: directory
        owner: "{{ xname }}"
        mode: "0755"

    - name: "Copy index test page"
      template:
        src: "files/index.html.j2"
        dest: "/var/www/{{ server_host }}/index.html"
        mode: "644"

    - name: "Set up the HTTP Apache virtualhost"
      template:
        src: "files/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ server_conf }}"
        mode: "644"

    - name: "Set up the HTTPS Apache virtualhost"
      template:
        src: "files/apache-le.conf.j2"
        dest: "/etc/apache2/sites-available/{{ server_conf | replace('.conf', '-le.conf') }}"
        mode: "644"

    - name: "Disable the default Apache site"
      command: /usr/sbin/a2dissite 000-default.conf
      register: output
      changed_when: output.rc != 0
      notify: Reload Apache

    - name: "Enable the HTTP Apache virtualhost"
      command: /usr/sbin/a2ensite {{ server_conf }}
      register: output
      changed_when: output.rc != 0
      notify: Reload Apache

    - name: "Install certbot"
      community.general.snap:
        name: certbot
        classic: true

    - name: "Request a certificate for {{ server_host }}"
      command: "/snap/bin/certbot certonly --non-interactive --agree-tos --apache -d {{ server_host }} -m {{ email }}"
      register: output
      changed_when: output.rc != 0
      args:
        creates: "/etc/letsencrypt/live/{{ server_host }}"

    - name: "Enable the Apache proxy modules"
      command: "/usr/sbin/a2enmod {{ item }}"
      register: output
      changed_when: output.rc != 0
      notify: Reload Apache
      with_items:
        - "proxy"
        - "proxy_http"

    - name: "Disable the default Apache site"
      command: /usr/sbin/a2dissite 000-default.conf
      register: output
      changed_when: output.rc != 0
      notify: Reload Apache

    - name: "Disable the default Let's Encrypt Apache site"
      command: /usr/sbin/a2dissite {{ server_conf | replace('.conf', '-le-ssl.conf') }}
      register: output
      changed_when: output.rc != 0
      notify: Reload Apache

    - name: "Diable the HTTP Apache virtualhost"
      command: /usr/sbin/a2dissite {{ server_conf }}
      register: output
      changed_when: output.rc != 0
      notify: Reload Apache

    - name: "Enable the HTTPS Apache virtualhost"
      command: /usr/sbin/a2ensite {{ server_conf | replace('.conf', '-le.conf') }}
      register: output
      changed_when: output.rc != 0
      notify: Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
